sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456AzQx.

  alioss:
    endpoint: os-cn-beijing.aliyuncs.com
    access-key-id: LTATStPeFLZsPPT8gG3LPW64
    access-key-secret: U6K1brOZ8gaOIXv3nXbu1GTUzy6Pd7
    bucket-name: sky-itcast

  minio:
    endpoint: http://192.168.11.144:9000
    access-key: minioadmin
    secret-key: minioadmin
    bucket-name: skytakeout

